version: '3.8'

services:
  # Your service definitions go here, properly indented
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-data:/data/db # This refers to the named volume

  app: # Example of your Spring Boot app service
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: 123456
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      - mongo

# Named volumes must be defined here, at the top level
volumes: # This 'volumes' key must be at the same indentation level as 'services' and 'version'
  mongo-data: # This named volume definition is correctly indented under 'volumes'
    # You can add driver, driver_opts, etc., here if needed.
    # driver: local